baseURL = "https://example.com"
title = "3D MAZE GAME"
languageCode = "en"
DefaultContentLanguage = "en" # Change this to change the site's language
theme = "hugo.386"
preserveTaxonomyNames = true

[params]
    # The name to display as main title in the home page
    mainpagetitle = "3D Maze Game"

    # The subtitle to display under the title in the home page
    mainpagesubtitle = "Welcome to 3D Gaming Experience!" 

    # The description of your website. It will be displayed in the home page
    mainpagedesc = "I have always had a passion for games and recently I have developed Inquisitive curiosity on how these games are built and the technologies behind them. Luckily, ALX provided an option for doing a 2D game project as the portfolio project. Since the best way to actually learn anything in the field of software engineering is by building, I decided to challenge myself and take on building the Maze-2d game by myself."

    # The name to display in the copyright section in the footer
    copyrightname = "Evans M. Kioko"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    copyrighturl = "http://muuo.codes"

    # Show the "built on Hugo" disclaimer
    showhugo = true

    # Urls for socia networks
    # facebook = "https://facebook.com"
    # twitter = "https://twitter.com"
    # linkedin = "https://linkedin.com"
    github = "https://github.com"
    # gitlab = "https://gitlab.com"

    # Enables or disables the loading animations. false activates them. Default is false.
    loadfastload = false

    # Sets the speed for the page loading effect. Default is 1.0.
    loadspeedfactor = 1.0

    # Enables or disables the second flyby cursor. Default is false.
    loadonepass = false

[params.copyright]
    name = "Evans M. Kioko"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    url = "http://muuo.codes"

    # Text to go before copyright information
    # prefix = "[hugo.386 theme by Max le Fou](https://gitlab.com/maxlefou/hugo.386)"

    # Text to go between copyright and hugo disclaimer (if enabled)
    # suffix = "Example site"

[menu]
  # This displays buttons in the navbar to access your contents
  [[menu.main]]
    identifier = "about" # An unique identifier for the button
    name = "About The Game"       # A display name for the button
    url = "/about/"      # The path to the content. It can lead to a single page (like here)
    weight = 10          # A number to order the buttons in the navbar

  [[menu.main]]
    identifier = "posts"
    name = "Blog"
    url = "/post/"       # The path can lead to a content folder too.
    weight = 20

 [taxonomies]
 category = "categories"
 tag = "tags"


[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
